### ISSUE TITLE
Add support for Tagalog

### ISSUE THREAD

**Issue by jqnatividad** [greyblake/whatlang-rs#104]
Tagalog is the national language of the Philippines, and Filipinos - per the [2021 We Are Social annual report](https://wearesocial.com/uk/blog/2021/01/digital-2021-the-latest-insights-into-the-state-of-digital/) are _"still the world’s biggest consumers of social media, spending an average of 4 hours and 15 minutes per day using social platforms – a full half an hour more than second-placed Colombians."_

I'm a native speaker, and if you can point me in the right direction, I can add Tagalog support.

**Comment by greyblake** [comment]
@jqnatividad I see.
Here are the steps:
* Copy the trigrams from Franc: https://github.com/wooorm/franc/blob/main/packages/franc/data.js#L30
* Paste them into https://github.com/greyblake/whatlang-rs/blob/master/misc/data.json in the Latin section
* Run `ruby misc/update_support_languages.rb` it should regenerate all relevant files
* Add a test sample into `tests/examples.json`

Thanks!
