### ISSUE TITLE
Add section in README: Who uses Whatlang?

### ISSUE THREAD

**Issue by greyblake** [greyblake/whatlang-rs#112]

**Comment by ManyTheFish** [comment]
[Meilisearch](https://github.com/meilisearch) via the [charabia crate](https://github.com/meilisearch/charabia). 😇

**Comment by greyblake** [comment]
Addressed in https://github.com/greyblake/whatlang-rs/commit/d2dfbdaa457a9dc6ff1a4f12858ee62392f0485c
