### ISSUE TITLE
Generate Languages with a Rust Build script

### ISSUE THREAD

**Issue by Dr-Emann** [greyblake/whatlang-rs#15]
The kind of code generation done by [lang_generator.rb](https://github.com/greyblake/whatlang-rs/blob/master/misc/lang_generator.rb) seems like it would be ripe for generation with a [build.rs](http://doc.crates.io/build-script.html) file. It can be set up to automatically be re-run when any of the source files change.

**Comment by greyblake** [comment]
I thought about replacing this somehow with macros, but I guess it's not possible to read data files with macros to build Rust AST.

Thanks, I'll take a look at `build.rs` when I have time.

**Comment by Dr-Emann** [comment]
It might also be possible to move the whatlang-ffi repo into a subfolder of this one, and generate the c headers automatically as well.
