### ISSUE TITLE
Link to whitepaper in README yields a 404.

### ISSUE THREAD

**Issue by jperras** [greyblake/whatlang-rs#33]
The README points to [`http://www.let.rug.nl/usa//~vannoord/TextCat/textcat.pdf`](http://www.let.rug.nl/usa//~vannoord/TextCat/textcat.pdf), which is (as of this moment), returning a 404.

**Comment by greyblake** [comment]
Thanks for the report.
Looks like that site is down.
I googled and found another source of the document: https://www.researchgate.net/publication/2375544_N-Gram-Based_Text_Categorization

**Comment by greyblake** [comment]
I just updated the README. Probably I need somehow to automate dead link checking in CI.
Thanks again for the report :+1:

**Comment by jperras** [comment]
Thanks for the link to the paper!
