### ISSUE TITLE
Too many public things

### ISSUE THREAD

**Issue by Dr-Emann** [greyblake/whatlang-rs#4]
I'm not sure it makes sense for things like [`whatlang::ARABIC_LANGS`](https://docs.rs/whatlang/0.2.0/whatlang/constant.ARABIC_LANGS.html) to be public, or [`get_trigrams_with_positions(..)`](https://docs.rs/whatlang/0.2.0/whatlang/fn.get_trigrams_with_positions.html)

**Comment by greyblake** [comment]
Yea, definitely these things shouldn't be public. I kept this in mind.
I will rearrange file structure a little bit later. As far as I've noticed, in solid Rust libraries, nobody keeps implementations in `lib.rs` file, it's used only to import/export functionality.

**Comment by greyblake** [comment]
Fixed in version 0.3.0 (see doc: https://docs.rs/whatlang/0.3.1/whatlang/)
