### ISSUE TITLE
Add comparison CLD2

### ISSUE THREAD

**Issue by jrmuizel** [greyblake/whatlang-rs#6]
It would be interesting to know how this library compares to cld2 https://github.com/CLD2Owners/cld2.

**Comment by greyblake** [comment]
@jrmuizel Hi! Sorry for delay. Do you mean perfomance?

**Comment by jrmuizel** [comment]
I was more interested in a comparison of the two techniques, but runtime performance, accuracy, and size would all be interesting.

**Comment by sanxiyn** [comment]
There is also [CLD3](https://github.com/google/cld3).

**Comment by greyblake** [comment]
Added a comparison with CLD2 in README.
