### ISSUE TITLE
C bindings

### ISSUE THREAD

**Issue by arrufat** [greyblake/whatlang-rs#8]
Thank you for this fast and easy to use library.
It would be even nicer if we could use it in non-Rust applications. Have you thought about providing C bindings?
Thanks in advance!

for reference:
https://github.com/kaegi/netinfo
https://github.com/kaegi/netinfo-ffi

**Comment by greyblake** [comment]
Hi! Thanks for the links and sorry for delayed reply.
I am personally not interested in this, and I don't really have good C experience (I know only basics, as any other programmer). 
If you are interested in this and have time to implemented, I would appreciate a pull request :)

**Comment by greyblake** [comment]
@arrufat I've started [whatlang-ffi](https://github.com/greyblake/whatlang-ffi) project.

It's still in development, but minimal working example you can find here: https://github.com/greyblake/whatlang-ffi/blob/master/examples/example.c
