### ISSUE TITLE
Use full english name for Lang Enum variants

### ISSUE THREAD

**Issue by Dr-Emann** [greyblake/whatlang-rs#9]
I think it would look cleaner to use the full name for the Lang enum. e.g `Lang::Mandarin` vs `Lang::Cmn`. If wanted, we could also expose a module which rexports the short names: e.g.
```rust
use whatlang::short_lang;
let russian = short_lang::rus;
```

**Comment by clarcharr** [comment]
I disagree; the standard language codes should be used instead.

Perhaps there could be an exposed `long_name` that does what you want.

**Comment by greyblake** [comment]
Hi! Thanks for suggestion. I guess it makes sense to use ISO codes.
Why? They allow to identify a language exactly, even if it's a dialect.
I know, the downside of this, it's not human readable and is not always obvious which code means which language unless you lookup the ISO table. 
I am planning to add a method to get a language name as a string in the future.

Thank you guys and sorry for delay.
