### ISSUE TITLE
Try to get rid of hashbrown

### ISSUE THREAD

**Issue by greyblake** [greyblake/whatlang-rs#98]
Try to use `std::collections::HashMap`.
Do benchmark, to ensure there is no regression in performance

**Comment by jqnatividad** [comment]
Pinging this issue @greyblake , as since Rust 1.36, hashbrown is now the HashMap implementation of the Rust standard library.

And the hashbrown folks benchmarked it too - https://github.com/rust-lang/hashbrown#performance

**Comment by greyblake** [comment]
@jqnatividad Thanks, I know.
I've tried to switch to std HashMap, but it hits performance, I am not sure exactly why.
You can also give it a try if you want to.

**Comment by jqnatividad** [comment]
Hi @greyblake , I went ahead as you suggested, but decided to bump hashbrown, and several other dependencies to their latest release.

**Comment by greyblake** [comment]
It does not look like hashbrown will go anywhere, benchmarks show that with `std::collections::HashMap` the `detect()` function is 2x slower.
See https://github.com/greyblake/whatlang-rs/pull/119
